name: docker.yml
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Solana version'
        required: true
        default: '1.18.15'
jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            runner: buildjet-16vcpu-ubuntu-2204
          - platform: "linux/arm64"
            runner: buildjet-16vcpu-ubuntu-2204-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
      - name: Set platform path name
        run: |
          echo "PLATFORM_PATH_NAME=${{ matrix.platform }}" | tr '/' '-' >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push specific docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            SOLANA_VERSION=${{ inputs.version }}
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PATH_NAME }}
          path: /tmp/digests/*
          if-no-files-found: error
  merge-images:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
          echo "FINAL_IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ inputs.version }}" >> $GITHUB_ENV
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-*
          path: /tmp/digests
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create merged image
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create -t ${{ env.FINAL_IMAGE_NAME }} $(printf '${{ env.IMAGE_NAME }}@sha256:%s' *)
